/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pchat;

import static java.awt.image.ImageObserver.WIDTH;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maria
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Chat
     */
    
    private ventana v;
    private String emisor;
    private String receptor;
    private PrincipalChat principal;
   
    
    
   
    public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }
    
    public Chat(String emisor, String receptor,PrincipalChat principal) {
        initComponents();
        v=new ventana();
        
        v.setVisible(true);
        v.setContentPane(this);
        this.principal=principal;
        this.emisor=emisor;
        this.receptor=receptor;
        this.nicks.setText(emisor + " hablando con " + receptor);
        v.setDefaultCloseOperation(WIDTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoMandar = new javax.swing.JTextArea();
        enviarMensaje = new javax.swing.JButton();
        nicks = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoMensajes = new javax.swing.JTextArea();

        textoMandar.setColumns(20);
        textoMandar.setRows(5);
        jScrollPane1.setViewportView(textoMandar);

        enviarMensaje.setText("Enviar");
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        nicks.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nicks.setText("jLabel1");

        textoMensajes.setEditable(false);
        textoMensajes.setColumns(20);
        textoMensajes.setRows(5);
        textoMensajes.setAutoscrolls(false);
        jScrollPane2.setViewportView(textoMensajes);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                        .add(18, 18, 18)
                        .add(enviarMensaje)
                        .add(39, 39, 39))
                    .add(layout.createSequentialGroup()
                        .add(nicks)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(nicks)
                .add(18, 18, 18)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 33, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(17, 17, 17))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(enviarMensaje)
                        .add(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void escribePantalla(String mensaje){
           String mensaje1;
           mensaje1=receptor + "-->" + mensaje +"\n";
           textoMensajes.append(mensaje1);
        
    
    }
    
    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        String mensaje;
        
            
            principal.enviarMensaje(textoMandar.getText(),receptor);
            mensaje=emisor + "-->" + textoMandar.getText()+"\n";
            textoMensajes.append(mensaje);
        
    }//GEN-LAST:event_enviarMensajeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nicks;
    private javax.swing.JTextArea textoMandar;
    private javax.swing.JTextArea textoMensajes;
    // End of variables declaration//GEN-END:variables
}
