/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package p2pchat;

import Datos.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;

/**
 *
 * @author maria
 */
public class PrincipalChat extends javax.swing.JPanel {

    private ClienteImpl cliente;
    private ventana v;
    private String nick;
    private HashMap<String,IClienteP2P> amigosConectados;
    private Vector amigosNombre;
    /**
     * Creates new form PrincipalChat
     */
    public PrincipalChat(ClienteImpl cliente, String nick) {
        initComponents();
        v=new ventana();
        this.cliente=cliente;
        amigosNombre= new Vector();
        listaAmigos.setListData(amigosNombre);
        v.setContentPane(this);
        v.setVisible(true);
        
    }

     public ventana getV() {
        return v;
    }

    public void setV(ventana v) {
        this.v = v;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void actualizaLista(Amigo amigo, boolean borrar){
        
        if(borrar!=true){
        amigosConectados.put(amigo.getNick(), amigo.getCliente());
        amigosNombre.add(amigo.getNick());}
        
        else{
        amigosConectados.remove(amigo.getNick());
        amigosNombre.remove(amigo.getNick());
        
        }
    
    }
    
    public void actualizaLista(ArrayList<Amigo> amigos){
        amigosConectados= new HashMap<String, IClienteP2P>();
        
        for(int i=0; i<amigos.size();i++){
        amigosConectados.put(amigos.get(i).getNick(), amigos.get(i).getCliente());
        amigosNombre.add(amigos.get(i).getNick());
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nickLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAmigos = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        iniciarChat = new javax.swing.JButton();
        cerrarSesion = new javax.swing.JButton();

        nickLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nickLabel.setText("jLabel1");

        listaAmigos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaAmigos);

        jLabel1.setText("Amigos conectados");

        iniciarChat.setText("Enviar mensaje");
        iniciarChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarChatActionPerformed(evt);
            }
        });

        cerrarSesion.setText("Cerrar sesión");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(nickLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 357, Short.MAX_VALUE)
                                .add(cerrarSesion))
                            .add(jLabel1)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(iniciarChat)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(nickLabel))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(cerrarSesion)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(iniciarChat)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        nickLabel.setText("Hola "+ nick);
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarSesionActionPerformed

    private void iniciarChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarChatActionPerformed
        // TODO add your handling code here:
        String nick= (String) listaAmigos.getSelectedValue();
    }//GEN-LAST:event_iniciarChatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JButton iniciarChat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaAmigos;
    private javax.swing.JLabel nickLabel;
    // End of variables declaration//GEN-END:variables
}
